# Generated by Django 5.2.7 on 2025-10-26 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária total')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('atualizada_em', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('LAB', 'Laboratório'), ('SAL', 'Sala de Aula'), ('AUD', 'Auditório'), ('OUT', 'Outros')], max_length=3)),
                ('capacidade', models.IntegerField(help_text='Número máximo de alunos')),
                ('localizacao', models.CharField(help_text='Prédio/Andar/Número', max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('atualizada_em', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROF', 'Professor'), ('SEC', 'Secretário'), ('COORD', 'Coordenador')], max_length=5)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('iniciado_em', models.DateField(blank=True, null=True)),
                ('encerrado_em', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('atualizada_em', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['-ano', '-semestre'],
                'unique_together': {('ano', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('numero_alunos', models.IntegerField(default=0, help_text='Número de alunos matriculados')),
                ('ativo', models.BooleanField(default=True)),
                ('desligamento_excepcional', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('atualizada_em', models.DateField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.perfilusuario')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.sala')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.semestre')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['semestre', 'dia_semana', 'hora_inicio'],
                'unique_together': {('semestre', 'sala', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
