# Generated by Django 5.2.7 on 2025-10-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(help_text='Ex: T01, T02', max_length=10)),
                ('numero_alunos', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.perfilusuario')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.semestre')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['disciplina', 'codigo_turma'],
                'unique_together': {('semestre', 'disciplina', 'codigo_turma')},
            },
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_turma', to='core.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.turma')),
            ],
            options={
                'verbose_name': 'Horário da Turma',
                'verbose_name_plural': 'Horários das Turmas',
                'ordering': ['turma', 'dia_semana', 'hora_inicio'],
                'unique_together': {('sala', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioAula',
        ),
    ]
