# Generated by Django 5.2.7 on 2025-10-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professor_alter_turma_professor_delete_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='andar',
            field=models.IntegerField(default=0, help_text='Use 0 para térreo/pilotis'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='localizacao',
            field=models.CharField(help_text='Prédio/Número', max_length=200),
        ),
    ]
